---
title: "From Quantum Mechanics to Electromagnetism"
render_with_liquid: false
published: false
format:
  html:
    html-math-method: mathjax
  pdf:
    pdf-engine: lualatex
header-includes:
  - \DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
  - \DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}
---


## Irrelevance of overall phase

In quantum mechanics, we are repeatedly told that the overall phase of the wave function is meaningless. This claim is supported with the argument that in the physical interpretation of the state in that formalism is in terms of its Hermitian square and not the state itself. 

For example, in the position-space wave function representation the state is described by a complex function  $\Psi(t,x,y,z)$ defines a probability density through the equation
$$
dP(t,x,y,z) = \left|\Psi(t,x,y,z)\right|^2dtdxdydz
$$
This probability density is unchanged under a phase rotation in which 
$$
\Psi \to e^{i\alpha} \Psi
$$
for any real $\alpha \in {\bf R}$. 
Thus, the desciptions in terms of the wave function $\Psi$ and $e^{i\alpha} \Psi$ are physically indistinguishable, and so they should be equivalent. 

This is all fine, but if we accept it, shouldn't we also take this to be equivalent to $\Psi^\prime = e^{i\alpha} \Psi$ where $\alpha =\alpha(t,x, y, z)$ is an entire function? After all, the probability density resulting from $\Psi^\prime$ is identical to that of $\Psi$. The catch is that this more general transformation, where the overall phase is different everywhere in space and time, is not a symmetry of the *Schrödinger equation*
$$
i\hbar \frac{\partial \Psi}{\partial t} = \hat H \Psi
$$
Let us describe this is some detail. 

If we rephase the wave funtion $\Psi \to  \Psi^\prime =\alpha \Psi$ with a constant $\alpha$, then the left-hand side changes to 
$$
e^{i\alpha}\left( i\hbar \frac{\partial \Psi}{\partial t}\right) 
$$
This shows that the left-hand side transforms just like $\Psi$ does when we replace $\Psi \to \Psi^\prime$. When an object transforms just like $\Psi$ does, we say it "varies" in the "same" way, or "co-varies". Such terms are called "covariant" because they change (vary) in the same (co-) way. 

Similarly, the right-hand side changes to 
$$
e^{i\alpha} \left( \hat H \Psi \right) 
$$
so the two sides change in the same way, and we can divide out by the invertable phase to recover the Schrödinger equation. This is why covariance is useful: The equation is not *invariant* (*i.e.* unchanged) because of the phase, but all terms vary the same way, and so in the end the whole equation is covariant and this gives a different, but equivalent equation. 

However, if the phase is time-dependent, 
$$
\frac{\partial \Psi}{\partial t}\to \frac{\partial \Psi^\prime}{\partial t} = e^{i\alpha} \frac{\partial \Psi}{\partial t} + i e^{i\alpha} \frac{\partial \alpha}{\partial t}\Psi
$$
and the new term messes up our previous conclusion. It is not covariant. Similarly, if the phase is space-dependent, then 
$$
\hat{\bf p} \Psi\to \hat{\bf p} \Psi^\prime = e^{i\alpha} \hat{\bf p} \Psi -i \hbar e^{i\alpha}\nabla\alpha \Psi 
$$
is also not covariant and the transformed Schödinger equation is not equivant to the original. If we could somehow make some changes to the equation that resore covariance, then we would be able to claim that the physics is unchanged under a local rephasing. This is what we will try to do next. 


### Local rephasing

For simplicity, we focus on time-independent rephasings, but we will allow the phase to be a function of position coordinates. When this condition holds $\partial \Psi/\partial t$ will be covariant, but 
$$
\hat{\bf p} \Psi({\bf x}, t) = -i\hbar \nabla \Psi({\bf x}, t)
$$
does not transform nicely under local rephasing $\Psi \to  \Psi^\prime$, because $\nabla \alpha\neq 0$ is messing up covariance. 

Can we fix it somehow? The problem is that $\hat {\bf p}$ is not misbehaving under the transformation, only $\Psi$ is and $\hat {\bf p}$ gets hung up on the bad phase. But what if we make a new $\hat {\bf p}$ we'll call the delinquent momentum $\hat {\pi}$ that transforms like, say
$$
\hat {\pi}^\prime = \hat {\pi} + i \hbar\nabla\alpha 
$$
For example, we could take ${\pi} ={\bf p} - i\hbar {\bf A}({\bf x})$ for some mischievous "function" that transforms like 
$$
{\bf A}\to {\bf A}^\prime = {\bf A} - \nabla \alpha
\tag{$*$}
$$

I'll admit that this seems very *ad hoc*, but that is what physicists do: make it work by hook or crook and try to justify it later. If it doesn't work, you look like an idiot, apologize, and hope people will forget. But if it work, you'll look like a genius!

Anyway, let's try this stupid-looking idea. First, we check covariance: 
\begin{align}
\hat{\pi} \Psi =\left(\hat{\bf p} - i\hbar {\bf A}\right) \Psi 
    &\to \left(\hat{\bf p} - i\hbar {\bf A}^\prime\right) \Psi^\prime \cr
    &= e^{i\alpha}\left(\hat{\bf p} - i\hbar {\bf A}+i\hbar \nabla \alpha\right) \Psi -i \hbar e^{i\alpha}\nabla\alpha \Psi \cr
    &= e^{i\alpha}\left(\hat{\bf p} - i\hbar {\bf A}\right) \Psi 
    = e^{i\alpha}\hat{\pi}\Psi 
\end{align}
So $\hat{\pi} \Psi \to e^{i\alpha}(\hat{\pi}\Psi)$ just like $\Psi$! Covariance!

Buoyed by this small success, we replace everywhere ${\bf p}\to {\pi} = {\bf p} - i \hbar {\bf A}$, and check the transformation properties. To do this, notice the following trick: since $(\hat{\pi} \Psi)^\prime = e^{i\alpha} (\hat{\pi} \Psi)$ and since $\Psi^\prime =e^{i\alpha} \Psi$, then that must mean that 
$$
\hat{\pi}^\prime = e^{i\alpha} \hat{\pi} e^{-i \alpha}
$$
This is great, because it make covariance of iterated momenta trivial to check: 
$$
(\hat{\pi} \hat{\pi} \Psi)^\prime = \hat{\pi}^\prime \hat{\pi}^\prime \Psi^\prime
= e^{i\alpha} \hat{\pi} e^{-i \alpha} e^{i\alpha} \hat{ \pi} e^{-i \alpha} e^{i\alpha} \Psi 
= e^{i\alpha} \hat{\pi}\Psi 
$$

With this result, it is clear that the covariantized Hamiltonian 
$$
\hat H = \frac{{\pi}^2}{2m} + \hat V
$$
is covariant:
$$
\hat H = e^{i\alpha}\frac{{\pi}^2}{2m}e^{-i \alpha} + \hat V
= e^{i\alpha}\left(\frac{{\pi}^2}{2m} + \hat V\right) e^{-i \alpha}
= e^{i\alpha}\hat H e^{-i \alpha}
$$
Thus, the Schrödinger equation is covariant now and all it cost was the introduction of the vector field ${\bf  A}$ with the weird non-covariant transformation law ($*$). 

### The gauge-invariant wave function

To understand better what we actually did, let's go back to the beginning and look at the wave function again. We have this $\Psi$ with an ambiguous phase $\Psi\sim \Psi^\prime$ for any $\Psi^\prime = e^{i\alpha} \Psi$. Can't we just get rid the this phase ambiguity? Why yes, now we can! Consider the line integral 
$$
\varphi(\gamma) = \int_\gamma {\bf A}\cdot d{\bf x}
$$
over some path $\gamma$ starting a point $p$ and ending at a point $q$. Then under a phase change ${\bf A}\to {\bf A}^\prime$ according to the rule ($*$), 
\begin{align}
\varphi'(\gamma) &= \int_\gamma {\bf A}'\cdot d{\bf x}
    = \int_\gamma {\bf A}\cdot d{\bf x} + \int_\gamma \nabla \alpha \cdot d{\bf x} \cr
    &=\varphi(\gamma) + \alpha(q)-\alpha(p)
\end{align}
by the fundamental theorem of line integrals. Now suppose for simplicity that whatever function $\alpha$ is, $\alpha(q)\to 0$ if $q$ is "far enough away". (We don't need to do this, but assuming this makes the analysis less messy.) Then instead of considering the wave function at $p$, let's consider the same wave function dressed up with a the line integral: We define
$$
\widetilde \Psi(p, t) = e^{i\int_q^p {\bf A}\cdot d{\bf x}}\Psi(p, t)
$$
where $\gamma$ is any path starting at a point $q$ where $\alpha=0$ and ending at the point $p$. Then our result above indicates that under a gauge transformation 
$$
\widetilde \Psi'(p, t) = e^{i\int_\gamma {\bf A}\cdot d{\bf x}}e^{-i\alpha(p)} e^{i\alpha(p)} \Psi(p, t) = \widetilde \Psi(p, t) 
$$
This dressed up version of $\Psi$ is completely invariant!

---

## The Aharonov-Bohm experiment 

** EXPLAIN AHARONOV-BOHM EXPERIMENT HERE **

---

## The magnetic field 

Using our dolled-up wave function, we can explain this effect easily: As the electron progresses through an ${\bf A}$ field in the Aharonov-Bohm modification of the double slit experiment, the usual phase accumulation $e^{\frac i\hbar \int_\gamma {\bf p}\cdot d{\bf x} }\Psi$ gains a line integral tail 
$$
e^{\frac i\hbar \int_\gamma {\bf p}\cdot d{\bf x} }\Psi
    \to e^{\frac i\hbar \int_\gamma {\pi}\cdot d{\bf x} }\Psi 
    = e^{\frac i\hbar \int_\gamma {\bf p}\cdot d{\bf x} }e^{ \int_\gamma {\bf A}\cdot d{\bf x} }\Psi
    =e^{\frac i\hbar \int_\gamma {\bf p}\cdot d{\bf x} }\widetilde \Psi
$$
After a full circuit (equivalent to double-slit interference), the accumulated phase is $e^{ \oint_\gamma {\bf A}\cdot d{\bf x} }$. But $\gamma$ is the boundary of the surface $\Sigma$ the the solenoid flux threads, so by the Green theorem (or whatever), 
$$
\oint_\gamma {\bf A}\cdot d{\bf x} 
    = \oint_{\partial \Sigma} {\bf A}\cdot d{\bf x} 
    = \int_\Sigma \nabla \times {\bf A}\cdot {\bf n} da 
$$
Here ${\bf n}$ is the unit normal vector to the oriented surface $\Sigma$ and $\partial \Sigma$ is math speak for "the boundary of $\Sigma$" (which in our case is exactly $\gamma$). Since this is the magnetic flux $ \int_\Sigma {\bf B}\cdot {\bf n} da $ through the solenoid, we are evidently supposed to conclude that 
$$
{\bf B} =  \nabla \times {\bf A} \tag{$**$}
$$

Wait what? We started with a local rephasing ambiguity and in the end, we are saying this is some form of the magnetic field! Does it make sense?? Well first of all, "gradients don't curl" so if we change ${\bf A}$ to ${\bf A}'={\bf A}+\nabla \alpha$, this definition of ${\bf B}$ does not change, so that's at least not blatantly wrong... 

Ah! But curls don't diverge so if ($**$) is correct then ${\bf B}$ must satisfy 
$$
\nabla \cdot {\bf B}= 0
$$
Does it? Yes.. actually that is a consequence of the Maxwell equation in the following form:
$$
\int_\Sigma {\bf B}\cdot {\bf n} da =0
$$
for any closed surface $\Sigma$. (In cool math notation, $\partial \Sigma = \emptyset$.) If $U$ is a volume with $\Sigma=\partial U$ as its boundary, this says that any flux line that leaves $U$ must come back to it: *i.e.* there are no magnetically charged particles. 
However, by the divergence theorem,
$$
0 = \int_\Sigma {\bf B}\cdot {\bf n} da = \int_U \nabla\cdot {\bf B} dv
$$
Since is true for any such $U$, it must be that $\nabla\cdot {\bf B}=0$. 

> ### Problem
>
> Calculate $[\hat {\pi}, \hat {\pi}]$ in the position space representation.

> ### Answer
>
> In components 
\begin{align}
\left[ \hat \pi_i , \hat \pi_j\right]
&=\left[ \hat p_i -i\hbar A_i , \hat p_j-i\hbar A_j \right]\cr
&=-i\hbar\left[ \hat p_i , A_j \right]
-i\hbar\left[  A_i , \hat p_j \right]
\cr
&=(-i\hbar)^2 \nabla_iA_j 
-(-i\hbar)^2\nabla_jA_i
\cr
&=-\hbar^2 \left( \nabla_iA_j - \nabla_jA_i\right)
\end{align}
>
> but this is the curl again, so the canonical commutation algebra has been deformed to
\begin{align}
\left[ \hat x^i , \hat x^j\right]=0
\quad ~&~\quad
\left[ \hat \pi_i , \hat x^j\right]=-i\hbar \delta_i^j\ 1
\quad\quad \cr
\left[ \hat \pi_i , \hat \pi_j\right]&=-\hbar^2 \varepsilon_{ijk}B^k
\end{align}

A lot just happened. Not only did we discover a Maxwell equation, we
* stumbled on it through *quantum mechanics* even though classical electrodynamics supposedly has nothing to do with quantum mechanics
* we solved it in terms of the so-called **vector potential** ${\bf A}$
* we also understand in what sense the vector potential is both more fundamental but also less real than the magnitic field:
    * It's less real, because it is not covariant: we can completely change it's functional form by adding the gradient of any function we want, so that cannot correspond to anything we measure directly; it's ambiguous
    * It's more fundamental in the sense that electrons couple directly to ${\bf A}$ and not ${\bf B}$. ${\bf B}$ appears in equations of motion, but ${\bf A}$ appears directly in the Schödinger equation.
* we understood the mysterious Aharonov-Bohm experiment. 

## Relativity?

I promised we would relax the restriction $\partial \alpha/\partial t=0$, so let's do that. The easiest way (hindsight is 20-20; look it up kids!) is to go back to the line integral dressing factor. Now that we know we can make the wave function invariant, that's a good place to look. The line integral has ${\bf A}\cdot d{\bf x}$, so what about a $dt$ term? Since this is a scalar, the most natural thing is 
$$
-c\phi\ dt+{\bf A}\cdot d{\bf x}
$$
where $c$ is the speed of light. The sign is there because of a convention in electricity and magnetism we will discuss later. The reason to introduce the speed of light is that $ct$ has the same physical dimension (*i.e.* length) as the Cartesian $x$, $y$, and $z$ we are so in love with. In fact, if we denote $x^1:=x$ and $x^2:=y$ and $x^3:=z$ as I mean when I write $d{\bf x}$, perhaps I should define $x^0:=ct$ while I'm at it! Then I can even set $A_0:=-\phi$ and just write the whole line integral in space and time as
$$
c\phi\ dt+{\bf A}\cdot d{\bf x}
    =A_0 dx^0+{\bf A}\cdot d{\bf x}
    = \sum_{\mu=0}^3 A_\mu dx^\mu 
    =:A_\mu dx^\mu 
$$
In the last step, we are following Einstein's suggestion to just drop all the tedious summation signs over every index that is repeated, since this is (nearly) unambiguous: If you are summing, the indices always come in repeated pairs and if you want space-time symmetry, you need to sum. So any repeated index is assumed to be summed. This is called the "Einstein summation convention".

OK! Where were we going with this? Oh yeah, how should $\phi$ transform is we want to keep all the nice properties we had before? Well when it was ${\bf A}$, the rule was ${\bf A}'={\bf A} + \nabla \alpha$, which are space derivatives. So the right thing to do is to have $\phi' = \phi +\partial \alpha/\partial t$. Certianly if our new definition of the invariant wave function is 
$$
\widetilde \Psi = e^{i\int_\gamma A_\mu dx^\mu}\Psi
$$
then yes, this will work because the phase (called a **Wilson line** by the way) will reconstitute the complete $\alpha(p)$ by the fundamental theorem of line integrals, which is now in spacetime and not just space.

But! Now we can figure out the spacetime version not only of the ${\bf B}$ field but also half of the Maxwell equations, since we will get the ${\bf E}$ version of what we found by accident before for ${\bf B}$ by following the same argument! 

Imagine a loop $\gamma$ in space and time. Let $\Sigma$ be *any* surface for which $\gamma$ is the boundary, *i.e.* $\partial \Sigma = \gamma$. Then let's spam the Green theorem again: 
$$
\int_\gamma A_\nu dx^\nu 
    =\int_{\partial \Sigma} A_\nu dx^\nu  
    =\int_{\Sigma} (\partial \times A)\cdot {\bf n} da
$$
Looks nice right? Yeah, except it doesn't mean anything!
* What is the vector normal to a surface in 4D??
* What does $\partial \times A$ mean?

Actually, these problems are an artifact of poor choices made in your multivariable calculus classes. It all started with the misleading statement that "vectors have direction and magnitude" and then it got progressively worse with "transposing" column vectors into row vectors, defining the gradient as a vector, and worst of all, introducing the right-hand rule and cross product, *which only exist in 3 dimensions*. So let's try to undo some of the damage, so we can move on. Let's agree with the working definition that a 3D vector $\bf v$ is a $3\times 1$ column of real numbers. (This is not the real definition, but it will work fine.) Lets also agree that these three numbers are labeled by $v^1$ for the top one, $v^2$ for the middle one, and $v^3$ for the bottom one. Together these **components** will be called $v^i$ where the **index** $i$ takes the three values $i=1,2,3$, for example
$$
{\bf v} 
= \begin{pmatrix} v^1\\v^2\\ v^3 \end{pmatrix} 
= \begin{pmatrix} \sqrt{\pi}\\ 0 \\ -1 \end{pmatrix}
$$
Another really good example is the "infinitesimal displacement" vector
$$
\left(dx^i\right) = \begin{pmatrix}dx\\dy\\dz\end{pmatrix}
$$
Now let's calculate the partial derivatives of a function $f(x^i)$ of three variables $x^1=x$, $x^2=y$, and $x^3=z$. This naturally looks like $\partial f/\partial x^i$. Here the index is "up" but it is in the numerator. This turns out the mean that the natrual arrangement is
$$
\frac{\partial f}{\partial x^i} = \left( \frac{\partial f}{\partial x}, \frac{\partial f}{\partial y}, \frac{\partial f}{\partial z}\right)
$$
The reason this arrangement is correct is that this matix arrangement naturally pairs with the first for the differential of $f$; a $1\times 3$ combines with a $3\times 1$ to give a $1\times 1$ matrix:
$$
df = dx^i \frac{\partial f}{\partial x^i} \tag{$***$}
$$
Let us further define the shorthand $\partial_i := {\partial f}/{\partial x^i}$ so that 
$$
df = dx^i \frac{\partial f}{\partial x^i} = dx^i \partial_i f
$$

--- 

### Dot product and gradient

Notice that the previous formula is *not* the same as $df = d{\bf x} \cdot \nabla f$. In fact, I have not defined what $\nabla$ is *and* I have not introduced a dot product. In fact, neither of these are necessary to write ($***$), because ($***$) is simply the chain rule of calculus.
I will now do both.

Suppose that I were to give you a rule $\langle - , - \rangle$ for taking any two vectors ${\bf v}$ and ${\bf w}$ and giving you a number $\langle {\bf v} , {\bf w} \rangle \in {\bf R}$. If this rule satisfies various conditions (symmetry, nondegeneracy, positivity), then it is called an **inner product** or **metric**. The most famous is the Euclidean one
$$
\langle {\bf v} , {\bf w} \rangle = v^1w^1+v^2w^2+v^3w^3
$$
But, in general the different terms could have different weights and there could even be cross-terms like $v^2 w^3$ (as long as there is also a term $v^3 w^2$ for symmetry). Now that my vector space is equipped with an inner product, I can introduce the notion of gradient: The gradient of a function, denoted $\nabla$ is a vector that has the property that *when plugged into the inner product with another vector ${\bf v}$ computes the directional derivative*
$$
\langle {\bf v} , \nabla f \rangle = v^i \frac{\partial f}{\partial x^i} \quad \quad \forall {\bf v}\in {\bf R}^3
$$

I will now go into more detail about components, because then I can use explicit symbols to emphasize what is happening here. Going back to the Euclidean inner product, let me write it in an unnecessarily complicated-looking way:
$$
\langle {\bf v} , {\bf w} \rangle = \sum_{i=1}^3 \sum_{j=1}^3 v^i \delta_{ij} w^j =  \delta_{ij} v^i w^j 
$$
Here I am defining the **Kronecker symbol**
$$
\delta_{ij} = \begin{cases}
1 & \textrm{if }i=j \\
0 & \textrm{otherwise}
\end{cases}
$$
and I dispensed with the superfluous summations again. Note that I can define another $\delta^{ij}$ to be the inverse of the first one in the sense that $\delta_{ik}\delta^{kj} = \delta_i^j$ is the unit matrix. Now I can finally define the components of $\nabla f$ in terms of those of $df$: 
$$
(\nabla f)^i = \delta^{ij} \frac{\partial f}{\partial x^j}= \delta^{ij} \partial_j f
$$
We see that we need the *inverse metric* to define the gradient, whereas we did not need anything, when we defined the differential $df$. So how does the formula connecting them work? You have to undo the inverse metric you *just introduced*: 
$$
\partial_i f = \delta_{ij} (\nabla f)^j =  \delta_{ij} \delta^{jk} \partial_k f
$$

---

### Cross produce

The next problem we confront is the cross product. This is a structure that takes an ordered pair of vectors $({\bf u}, {\bf v})$ and gives you a new vector ${\bf w}$ which is defined to have the following components 
$$
{\bf w} = \begin{pmatrix}v^2 w^3-v^3 w^2\\v^3 w^1-v^1 w^3\\ v^1 w^2-v^2 w^1\end{pmatrix}
$$
Note that this assignment is invariant under cyclic permutations and is anti-symmetric under the switch $({\bf u}, {\bf v})\mapsto ({\bf v}, {\bf u})$. The standard notation is to write ${\bf w} = {\bf u}\times {\bf v}$. 
So what is the problem with that? Well, for starters, what is this supposed to be in 2D? What about 4D? Are we claiming Green's Theorem only works in 3D?? The issue is that we are insisting that the result is another vector, when really what we wanted was the area of the oriented parallelogram spanned by the two vectors, which is why you could write it as the determinant of a matrix of ${\bf u}, {\bf v}$, and a unit vector. 

Let's introduce a new symbol to make this more explicit. This symbol will have 3-indices $i, j$, and $k$ all taking values $i,j,k=1, 2, 3$ (for now) such that
$$
\varepsilon_{ijk} = \begin{cases}
+1 & \textrm{if }(i,j,k)=(1,2,3)\textrm{ or } (2,3,1)\textrm{ or } (3,1,2)\\
-1 & \textrm{if }(i,j,k)=(2,1,3)\textrm{ or } (1,3,2)\textrm{ or } (3,2,1)\\
0  & \textrm{otherwise}
\end{cases}
$$
This is called the **Levi-Cevita** (*lev-ee che-vee-tah*) symbol and what it does for us is keep track of signed permulations of 3 elements. Volumes in 3D are signed permutations of 3 elements so for any 3 vectors ${\bf u}, {\bf v}$, and ${\bf w}$, the volume of the parallelepipid spanned by the ordered list $({\bf u}, {\bf v}, {\bf w})$ is $\varepsilon_{ijk}u^iv^jw^k$. This is also the determinant of the matrix with columns $({\bf u}, {\bf v}, {\bf w})$ and so for any linear operator with matrix $M^i{}_j$, the determinant is given by 
$$
\varepsilon_{lmn} M^l{}_i M^m{}_j M^n{}_k = \det(M) \varepsilon_{ijk}
$$
Finally, I can write the components of the cross product of an ordered pair of vectors $({\bf u}, {\bf v})$ as $\varepsilon_{ijk} u^j v^k$
Note, however, that as a "vector", this is a "row vector" and not a "column vector". We can "fix" that, but it will cost us another factor of the inverse metric, so finally, the cross product is 
$$
w^k=\delta^{kl}\varepsilon_{lij} u^i v^j
$$
Note that $\varepsilon_{kij} u^i v^j = \frac12 \varepsilon_{kij} (u^i v^j-u^jv^i)$, so this is *quite a mess* we are making just to talk about the antisymmetric combination $u^iv^j -u^jv^i$. 

Now anti-symmetric combinations exist in any dimension, and this is in fact the right answer for the area of a parallelogram in 2D. All you need is $u^1 v^2-u^2v^1 = \varepsilon_{ij}u^iv^j$, and, of course you could do this in 4D as $\varepsilon_{ijkl}u^kv^l$. So we see the problem: In exactly 3D, the Levi-Cevita symbol has the correct number of indices to give back something that looks like a vector, and *this will never happen again in any other dimension*. 

> Problem
>
> Define a second Levi-Cevita tensor by
$$
\varepsilon^{ijk} = \begin{cases}
+1 & \textrm{if }(i,j,k)=(1,2,3)\textrm{ or } (2,3,1)\textrm{ or } (3,1,2)\\
-1 & \textrm{if }(i,j,k)=(2,1,3)\textrm{ or } (1,3,2)\textrm{ or } (3,2,1)\\
0  & \textrm{otherwise}
\end{cases}
$$
> (Yes, it looks exactly like the old one, but the indices are "up".)
>
> Show that:
> 1. $\varepsilon_{ijk}\varepsilon^{ijk}=3!$
> 2. $\varepsilon_{ikl}\varepsilon^{jkl}=2\delta_i^j$
> 3. $\varepsilon_{ijm}\varepsilon^{klm}=(\delta_i^k\delta_j^l-\delta_j^k\delta_i^l)$
> 4. $\varepsilon_{ijk}\varepsilon^{lmn}= \delta_i^l\delta_j^m\delta_k^m \pm 5$ more terms with each possible permutation of the lower indices. Not that the signs are lined up with even and odd permutations.
>
> Hint: If you can do 4 first, the others follow.

> ### Answer
> 
> 1. We will get $\varepsilon_{123}\varepsilon^{123}=1$ six times: 3 for the cyclic permutions $123$, $231$, and $312$. The other 3 will be the odd permutations, like $\varepsilon_{213}\varepsilon^\varepsilon_{213}=(-1)(-1)=1$ so these also give three $+1$s.
> 2. We no that if $i\neq j$ then some index must be repeated on one of the $\varepsilon$s which gives 0, so the RHS $\propto \delta_i^j$. Since $\delta_i^i=3$, comparison with 1. tells us the constant of proportionality is 2.
> 3. ... 

## Faraday-Maxwell tensor

Going back to our original problem: What is Green's Theorem in 4D? We were trying to make sense out of the last equality in
$$
\int_\gamma A_\nu dx^\nu 
    =\int_{\partial \Sigma} A_\nu dx^\nu  
    =\int_{\Sigma} (\partial \times A)\cdot {\bf n} da
$$
but that is not so difficult now: The derviative operator naturally has its index down so we need to focus on that: $\int_{\Sigma} (\partial \times A)\cdot {\bf n} da\to $ something like $\int_{\Sigma} \partial_\mu A_\nu dx^\mu dx^\nu$, but it needs to be antisymmetric in the indices, because that seemed important to the curl earlier. So really, we want something like $\partial_\mu A_\nu - \partial_\nu A_\mu$. This combination is so import, it is called the Maxwell tensor or Faraday tensor, or Maxwell-Faraday tensor or field strenght tensor, or ... you get the idea. Anyway, it is the correct version of the curl in 4D, and just like in 3D, it does not change under the $A/A'$ ambiguity $A_\mu\to A_\mu+\partial_\mu \alpha$ 

> ### Problem
>
> Prove this by direct calculation.

> ### Answer
>
> Since partial derivatives commute $\partial_\mu \partial_\nu \alpha = \partial_\nu \partial_\mu$,
\begin{align}
F_{\mu\nu}' &= \partial_\mu A_\nu' - \partial_\nu A_\mu'\cr
    &= \partial_\mu A_\nu - \partial_\nu A_\mu +  \partial_\mu \partial_\nu \alpha - \partial_\nu \partial_\mu \alpha\cr
    &=F_{\mu\nu}
\end{align}

We are almost there, but we need to figure out what $F_{\mu\nu}dx^\mu dx^\nu$ means. In calculus we learn that $dxdy=dydx$ because integrals commute or something like that, but that is again an unforced error. We usually want *oriented* areas, and if we switch orientation, the integral flips sign! So really, we should be writing $dxdy=-dydx$! We have a symbol for this: For any two differentials $df$ and $dg$, we define the **wedge product** $df\wedge dg$ so that 
$$
dg\wedge df = -df\wedge dg
$$
Then $dx^\mu \wedge dx^nu$ is antisymmetric and therefore 
$$
\int_\gamma A_\nu\ dx^\nu 
    =\int_{\Sigma} \partial_\mu A_\nu\ dx^\mu \wedge dx^\nu
$$
checks all our boxes:
* It does what Green's is supposed to: relate a surface integral of a curl to a line integral aroudn a the boundary of the surface.
* It doesn't rely on metrics (they appear nowhere in this construction).
* The left-hand side is unambiguous under the shift by the fundamental theorem of line integrals.
* The righthand side is **manifestly** unambiguous because it is constructed "as a curl".

> ### Problem
>
> Recall that when the fields $\phi$ and ${\bf A}$ are time-independent, then ${\bf E}=-\nabla \phi$ and ${\bf B}=\nabla \times {\bf A}$.
> 
> a. Use this to calculate the components of the Maxwell tensor. Note that the electric field has a part that is not zero if the fields are allowed to vary in time. 
>
> b. Show that if fields are allowed to vary in time, then
$$
\nabla \times {\bf E} = -\frac1c\frac{\partial {\bf B}}{\partial t}
$$
>
> c. Show that the result in b. is equivalent to the statement that
$$
\frac1c\frac{\partial }{\partial t} \Phi_B(\Sigma) = -{\mathcal E}
$$
> for any fixed surface $\Sigma$ (*i.e.* not changing in time). Here $\Phi_B(\Sigma)$ is the magnetic flux through the surface, and $\mathcal E$ is the **[electromotive force](https://en.wikipedia.org/wiki/Electromotive_force)**. Which law from electricity and magnetism did you just rediscover?
>
> d. Show that the law in c. and the statement that there are no magnetic monopoles both follow from the formula
$$
\partial_\lambda F_{\mu \nu}
+\partial_\mu F_{\nu\lambda}
+\partial_\nu F_{\lambda \mu}=0
\tag{\dagger}
$$

> ### Answer
>
> a. The Maxwell tensor is $F_{\mu\nu}=\partial_\mu A_\nu - \partial_\nu A_\mu$, and we want to calculate $F_{0i}$ and $F_{ij}$. We will start with
$$
F_{ij} = \partial_i A_j - \partial_j A_i =  \varepsilon_{ijk} (\nabla \times {\bf A})^k = \varepsilon_{ijk}{\bf B}^k
$$
> so ${\bf B}^k = \frac12 \varepsilon^{lij}F_{ij}$.
> Similarly,
$$
F_{0i} = \partial_0 A_i - \partial_i A_0 =  \left( \frac1c\frac{\partial {\bf A} }{\partial t} + \nabla \phi\right)_i
$$
> so evidently $E^i = - \delta^{ij}F_{0j}$, so the electric field is
$$
{\bf E} = - \nabla \phi - \frac1c\frac{\partial {\bf A} }{\partial t} 
$$
> b. Note that this implies that a magnetic vector potential that is changing in time generates an electric field. If we take the curl of the definition above, we dervive that 
$$
\nabla \times {\bf E} = - \nabla \times \nabla \phi - \frac1c\frac{\partial }{\partial t} \nabla \times {\bf A} 
$$
> The first term vanishes because "gradients don't curl", and the second term is $-\frac1c\partial {\bf B}/\partial t$. 
>
> c. We can integrate the whole equation from b. over the surface $\Sigma$. Since the surface is not changing in time, we can switch the order of integration and differentiation of ${\bf B}$ which gives the magnetic flux $\Phi_B(\Sigma)=\int_\Sigma {\bf B}\cdot d{\bf a}$. Thus 
$$
\frac{\partial \Phi_B}{\partial t} = - \int_\Sigma \nabla \times {\bf E} \cdot d{\bf a}  
$$
> The claimed result now follows from Green's theorem again and the definition of the electromotive force. This is the Faraday-Lentz law of induction.
>
> d. If all the components are spacial (*i.e.* not the 0-component), then
$$
0=\partial_k F_{ij}
+\partial_i F_{jk}
+\partial_j F_{ki}
=\frac1{3!}\varepsilon_{ijk} \varepsilon^{mnp}\partial_p F_{ij}=\frac1{3!}\varepsilon_{ijk} \varepsilon^{mnp}\varepsilon_{mnq}\partial_p B^q
=\frac1{3}\varepsilon_{ijk} \delta^{p}_{q}\partial_p B^q
$$
> but this is proportional to $\nabla \cdot {\bf B}$. Next, we let $\lambda =0$ and $\mu$ and $\nu$ be spacial:
$$
0=\partial_0 F_{ij}
+\partial_i F_{j0}
+\partial_j F_{0i}
=\partial_0 F_{ij}
-\partial_i F_{0j}
+\partial_j F_{0i}
$$
> since this is antisymmetric in $ij$, we can pull out an $\varepsilon$. This is equivalent to just contracting the formula with $\varepsilon^{ijk}$, so lets do that (with a factor of $\frac12$ for convenience):
\begin{align}
0&=\frac12 \partial_0 \varepsilon^{ijk}F_{ij}
-\frac12\varepsilon^{ijk}\partial_i F_{0j}
+\frac12\varepsilon^{ijk}\partial_j F_{0i}\cr
&=\partial_0 B^k + \varepsilon^{ijk}\partial_i E_j
=\frac 1c \frac\partial{\partial t} B^k + (\nabla \times {\bf E})^k
\end{align}
> Taken together, these are the source-free Maxwell equations we were looking for. 

Notice that we casually derived both $\nabla \cdot {\bf B}=0$ and $\partial \Phi_B/\partial t = -c{\mathcal E}$ from a single equation in spacetime. In differential form notation, this equation is simply 
$$
dF=0
$$

> ### Problem
>
> Check this statement. Recall that the differential $d=dx^\mu \partial_\mu$ of some form has two parts: the derivative $\partial_\mu$ acting on the coefficients and the differential element $dx^\mu$ which has to be wedged with the differential element of the form. 

> ### Answer
>
> The Faraday-Maxwell 2-form is $F=F_{\mu \nu}\ dx^\mu \wedge dx^\nu$, so
$$
dF= \partial_\lambda F_{\mu\nu}\ dx^\lambda \wedge \left( dx^\mu \wedge dx^\nu\right) = \partial_\lambda F_{\mu\nu} \ dx^\lambda \wedge  dx^\mu \wedge dx^\nu
$$
> But $dx^\lambda \wedge  dx^\mu \wedge dx^\nu$ is totally anti-symmetric on $\lambda$, $\mu$, and $\nu$, and therefore the coefficient of $dF=0$ is just the previous form of the Maxwell equation ($\dagger$), up to a factor of 3. 

> ### Problem
>
> a. Check that on any differential (*i.e.* of any degree)
>
$$
d^2 = 0
$$
>
> b. Use this to show that
$$ 
dF=0 \quad \Leftrightarrow \quad F=dA
$$

> ### Answer
>
> a. A differential form $\omega$ of degree $p$ is of the form $\omega =\omega_{i_1 \cdots i_p}dx^{i_1}\wedge \dots dx^{i_p}$. Therefore
\begin{align}
d^2\omega &= d\left(\partial_{j}\omega_{i_1 \cdots i_p}dx^{j}\wedge dx^{i_1}\wedge\dots dx^{i_p}\right)\cr
&= \partial_k\partial_j \omega_{i_1 \cdots i_p}\ \ dx^{k}\wedge dx^{j}\wedge dx^{i_1}\wedge\dots dx^{i_p}
\end{align}
> But the wedge is anti-symmetric in $ij$ and the double partials are symmetric, so the whole thing vanishes. I accidentally did this with spacial indices, but the arguement is the same regardless. 
>
> b. Since $d^2=0$ on $A$, $dF=d^2A=0$. On the other hand, from multivariable calculus, whenever $dF=0$ in a contractable region of space (*i.e.* it has no "holes"), then there is some set of functions whose derivatives solve this equation. In the case at hand, this means that there is a form of degree 1 which we call $A$ by convention, for which $F=dA$.

## Stokes theorem done right

We have just defined generalizations of vectors and matrices. In the math(ematical physics) they are called **differential exterior forms**. The number of $dx\wedge$ terms appearing is called the degree of the form, and often we abbreviate to just $p$-forms. The vector with the index down is the component of a 1-form. An antisymmetric matrix with both indices down is a 2-form. A function is a 0-form, *et cetera*. Differential exterior forms of degree $p$ can be paired with appropriately smooth subsets of ${\bf R}^n$: 3-forms can be integrated over volumes, 2-forms over surfaces, 1-forms over lines, and 0-forms can be summed over collections of points. 

Let $\omega$ be an exterior differential form of degree $p$. Then $d\omega$ is an exterior differential form of degree $p+1$. If $U$ is some $(p+1)$-dimensional subset of ${\bf R}^n$, then $\int_Ud\omega\in {\bf R}$ is some number. Actually, so is $\int_{\partial U}\omega\in {\bf R}$ for that matter. In fact, we have already seen from a handful of examples that these two numbers are equal. This is the general form of the Stokes theorem:
$$
\int_Ud\omega = \int_{\partial U}\omega
\tag{\dagger\dagger}
$$

> ### Problem
>
> Use this form of Stokes' theorm together with the result of the previous problem to show that:
>> The boundary of a boundary is empty.
>
> In other words show that $\partial^2 U =\emptyset$ for all regions $U$. 

> ### Answer
>
> ...

## Charges and currents

To proceed, we need to figure out how to get the other Maxwell equations which are Coulomb/Gauß and Ampère's laws. The first is that over any closed surface $\Sigma$, the charge $Q(\Sigma)$ inside that surface is given by integrating the electric field over that surface
$$
Q(\Sigma) = \int_\Sigma {\bf E}\cdot d{\bf a}
$$
(or $\int {\bf E}\cdot {\bf n}\ da$ if that's more familiar). 
Let $U$ be the region for which $\Sigma=\partial U$ is the boundary. Then we can rewrite the equation above using the divergence theorem: 
$$
Q(U) = \int_U \nabla \cdot {\bf E}\ dv
$$
In general the charge $Q$ can be distributed throughout the region $U$, often continuously. Because of this, we define the charge density $\rho({\bf x})$: for any point with coordinates ${\bf x}$, the charge in an infinitesimal box of sides $dx$, $dy$, $dz$ is $dQ=\rho({\bf x})dx\wedge dy\wedge dz$. Thus $Q(\Sigma)=\int_U\rho({\bf x})dx\wedge dy\wedge dz$.

> ### Problem
>
> a. Show that you can rewrite the Gauß law as
$$
\nabla \cdot {\bf E} = \rho
$$
>
> b. Suppose this equation is a special case of some 4D equation of the form $\partial_\mu G^{\mu \nu}= j^\nu$, with $G^{\mu \nu}$ some version of $F_{\mu \nu}$, but with the indices up instead of down. Explain how to make sense of this, and what this means for the temporal components of $G^{\mu \nu}$ and $j^\mu$. You should assume that $G$, like $F$, is anti-symmetric.
>
> c. Write out what the spacial components $\nu=i$ look like in multivariable calculus notation, and discuss what you think it means. Can you identify this equation?

> ### Answer
>
> a. According to the problem statement
$$
\int_U\rho({\bf x})dx\wedge dy\wedge dz = Q(\Sigma) = \int_U \nabla \cdot {\bf E}\ dx\wedge dy\wedge dz
$$
> Since this is true for all regions $U$, it must be that the integrands agree: $\rho=\nabla \cdot {\bf E}$.
>
> b. An equation like $\partial_\mu G^{\mu \nu}=j^\nu$ has temporal components ($\nu=0$) and spacial ones $\nu=j$. Let's look at the temporal ones first: Setting $\nu=0$ results in
$$
j^0 = \partial_\mu G^{\mu 0} =\partial_i G^{i 0}
$$
> because $G$ is anti-symmetric, which is why there are no $G^{00}$ components.
> The resulting equation could be the Gauß law provided $\rho\propto j^0$ and the electric field components $E^i\propto G^{0i}$. If it is permissible to scale the components to have values $\pm1$, then, for example $j^0=\rho$ and $G^{0i} = - G^{i0} = -E^i$.
>
> c. The spacial components of the equation are $\partial_0 G^{0i} +\partial_j G^{ji} = j^i$. By what we just derived, the first term is the time derivative of $-{\bf E}$. We next define a 3-vector $\bf j$ and another one ${\bf G}$ with components $G_k = \frac12 \varepsilon_{kij} G^{ij}$. Then the equation becomes
$$
-\frac1c \frac {\partial {\bf E}}{\partial t} + \nabla \times {\bf G} = \frac1c {\bf j}
$$
> The first factor of $\frac1c$ is needed because $x^0=ct$. We now explain the second such factor and identify the equation. 
> 
> This equation looks a lot like Ampère's law: Take a surface $\Sigma$ and define the ${\bf j}$-flux through it to be $I(\Sigma)=\int_\Sigma {\bf j} \cdot d{\bf a}$. Similarly, we define $\Phi_{\bf E}(\Sigma) = \int_\Sigma {\bf E} \cdot d{\bf a}$, so that $\int_\Sigma \nabla \times {\bf G}\cdot d{\bf a} = \int_{\partial \Sigma}{\bf G}\cdot d{\bf \ell}$, so 
$$
 c\ \int_{\partial \Sigma}{\bf G}\cdot d{\bf \ell} = I + \frac {\partial}{\partial t}\Phi_{\bf E} 
$$
> If ${\bf G}={\bf B}$, then this is the law of Ampère with Maxwell's modification called the **[displacement current](https://en.wikipedia.org/wiki/Displacement_current)**.

## The metric of spacetime

In the previous problem, we postulated a second tensor $G$ similar to $F$ but "of the opposite type". In components, we previously found 
$$
\left( F_{\mu \nu} \right) 
= 
\begin{pmatrix}
0 & E^x & E^y & E^z \\
-E^x & 0 & B^z & -B^y \\
-E^y & -B^z & 0 & B^x \\
-E^z & B^y & -B^x & 0
\end{pmatrix}
$$
but we also just found
$$
\left( G^{\mu \nu} \right) 
= 
\begin{pmatrix} 
0 & -E^x & -E^y & -E^z \\
E^x & 0 & B^z & -B^y \\
E^y & -B^z & 0 & B^x \\
E^z & B^y & -B^x & 0
\end{pmatrix}
$$

If we had a spacetime metric $\eta_{\mu\nu}$ and it's inverse $\eta^{\mu\nu}$
$$
\eta^{\mu\lambda}\eta_{\lambda\nu}=\delta_\nu^\mu
=\eta_{\nu\lambda}\eta^{\lambda\mu}
$$
then we could define $F^{\mu \nu} = \eta^{\mu\sigma}\eta^{\nu\rho}F_{\sigma \rho}$. If this version of $F$ is independent from $G$ then that would mean that there are two independent electromagnetic fields. Since this is not the case, we know that $G$ must be fixed by $F$. The simplest guess is that we should set $G^{\mu \nu}=\pm F^{\mu \nu}$. 

To be consistent with historical conventions we chose the $+$ sign. This is the correct thing to do in vacuum, but in more complicated materials there is a more complicated relation between $F$ and $G$ called the [constitutive relation](https://en.wikipedia.org/wiki/Constitutive_equation). For this reason, there are two additional symbols traditionally used in electromagnetic theory. The mixed space-time components of $G$ are written as ${\bf D}$ called the electric displacement and ${\bf H}$ called the magnetic intensity. 

In the remainder of these notes, we will assume the simplest constitutive relation which in components says $G^{\mu\nu} = F^{\mu\nu}$. 

> ### Problem
>
> Assuming all this, show that the metric and its inverse have components 
$$
\left( \eta_{\mu \nu} \right) 
= 
\begin{pmatrix}
-1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{pmatrix}
= \left( \eta^{\mu \nu} \right) 
$$

> ### Answer
>
> By comparing the results of our calculations above, we see that the components of $F_{0i}$ are the same as those of ${\bf E}$ and those of $F^{0i}$ the negatives of these. But
$$
F^{0i} = \eta^{0\mu} \eta^{i \nu} F_{\mu\nu}
= \eta^{00} \eta^{i j} F_{0j} + \eta^{0j} \eta^{i0} F_{j0} + \eta^{0j} \eta^{ik} F_{jk}
$$
> $F_{jk}$ is some component of the ${\bf B}$ field, so this term should not be there. Since $\eta_{ij}$ is a 3D spacial metric, it's probably required to be $\pm \delta_{ij}$, so we see that we should take $\eta^{0i}=0$. Intuitively, this makes sense because it would be very strange if lifting a spacial index makes it temporal. For example a current would become a charge. This also kills the second term, so we see that either $\eta^{00}=-1$ and $\eta^{ij}=\delta^{ij}$ or $\eta^{00}=1$ and $\eta^{ij}=-\delta^{ij}$. Both choices are possible, but the choices we have already made imply that we must pick the former. 

This form of the spacetime metric is called the **Minkowski metric**, and we are using what is called the "mostly plus" convention (a.k.a. east-coast metric). The opposite convention (which we cannot take because of choices me made already) is called the "mostly minus" convention (a.k.a. west-coast metric). 

Our convention has the advantage that it agrees with our intuition about 3D geometry. The other convention has the advantage of minimizing the appearance of certain signs in particle physics calculations. 

We can now put it all together and write the Maxwell equations as 
$$
\varepsilon^{\mu\nu\rho\sigma}\partial_\nu F_{\rho \sigma} = 0
\quad\quad \textrm{and}\quad\quad 
\partial_\mu F^{\mu \nu} = j^\nu
$$
We have already shown that the first is equivalent to 
$$
\nabla \cdot {\bf B} = 0
\quad\quad \textrm{and}\quad\quad 
\nabla \times {\bf E} = - \frac1c \frac {\partial {\bf B}}{\partial t}
$$
and the latter one is
$$
\nabla \cdot {\bf E} = \rho
\quad\quad \textrm{and}\quad\quad 
c \nabla \times {\bf B} = \frac {\partial {\bf E}} {\partial t} + {\bf j}
$$

## The Hodge dual

When we are allowed to use both a spacetime metric $\eta$ and a spacetime volume form $\varepsilon$, we can define an operation on called the Hodge duality operation on exterior differential forms. It is denoted by $*$ and is defined to take a $p$-form $\omega$ to an $(n-p)$-form $* \omega$, where $n$ is the dimension of the spacetime (which is equal to the degree of the volume form). In Minkowski space, for example, the components of $* \omega$ are defined by using $p$ factors of the (inverse) Minkowski metric $\eta$ to contract the $p$ indices of $\omega$ with $\varepsilon$. This leaves $n-p$ totally antisymmetric indices on $\varepsilon$ and so defines components of an $(n-p)$-form. Explicitly, 
\begin{align}
(* \omega)_{i_1\cdots i_{n-p}}
&=\frac1{p!} \varepsilon_{i_1\cdots i_{n-p}}{}^{j_i \dots j_p}\omega_{j_1\cdots j_p}
\cr
&=\frac1{p!} \varepsilon_{i_1\cdots i_{n-p}j_i \dots j_p}\eta^{j_ik_1} \dots \eta^{j_pk_p}\omega_{k_1\cdots k_p}
\end{align}

> ### Problem
>
> a. Calculate $\varepsilon^{0123}$. 
>
> b. Calculate the Hodge dual of the volume 4-form $\varepsilon$. What important quantity of the spacetime metric does it compute?
>
> c. Calculate the components of the Hodge dual of the Maxwell tensor. What is the duality operator doing to ${\bf E}$ and ${\bf B}$?
>
> d. Taking the dual twice in a row takes a $p$-form to a $p$-form. Calculate the components of $** \omega$.
>
> 

> ### Answer
>
> a. Raising the indices on $\varepsilon$ gives $\varepsilon^{0123}=\eta^{0\mu}\eta^{1\nu}\eta^{2\rho}\eta^{3\sigma}\varepsilon_{\mu\nu\rho\sigma}
= \eta^{00}\eta^{11}\eta^{22}\eta^{33}\varepsilon_{0123}$. There is one factor of $\eta^{00}=-1$ and $\varepsilon_{0123}=1$, so $\varepsilon^{0123}=-1$. In 
>
> b. $*\varepsilon = \frac1{4!} \varepsilon^{\mu \nu \rho\sigma}\varepsilon_{\mu \nu \rho\sigma}=\varepsilon^{0123}\varepsilon_{0123}= -1$. This is the determinant $\det(\eta^{-1})$.
>
> c. $(*F)_{0i} =\frac12 \varepsilon_{0i}{}^{jk}F_{jk}=\frac12\varepsilon_{ijk}F^{jk}=B_i$. Similarly, $(*F)_{ij} =\frac12 \varepsilon_{ij}{}^{\mu \nu}F_{\mu \nu}= \varepsilon_{ij}{}^{0 k}F_{0k}=-\varepsilon_{ijk}B^k$. This shows that Hodge maps ${\bf E}\to {\bf B}$ and ${\bf B}\to -{\bf E}$.
>
> d. Doing the operation in part c. twice gives ${\bf E}\to {\bf B}\to -{\bf E}$ so $**$ acts by multiplying by -1. Doing it on a 0-form is also easy because $*1=\varepsilon$, so from part b., $**1=*\varepsilon=-1$, so again, we find that it acts by multiplication by $-1$. A similar calculation on 1-forms gives
$$(**A)_\mu=\frac1{3!}\frac1{1!}\varepsilon_\mu{}^{\nu\rho\sigma}\varepsilon_{\nu\rho\sigma}{}^\lambda A_\lambda$$
> Doing the 0 component gives $\varepsilon_0{}^{ijk}\varepsilon_{ijk}{}^0=-\varepsilon_{0 ijk}\varepsilon^{0ijk}=+3!$. Note that permuting the 0 to the front gave an extra sign! Repeating this argument for the spacial components gives the same result. Evidently $**=(-1)^{p+1}$. 

> ### Problem
>
> a. Show that Maxwell's equations imply that the charge density $\rho$ and current density ${\bf j}$ satisfy the equation
$$
\frac1c \frac{\partial \rho}{\partial t}+\nabla \cdot {\bf j} = 0
$$
>
> b. Assume that both densities fall off (go to zero) outside of a (potentially enormous) ball as long as that ball is big enough. This is a reasonable physical requirement because if this were not the case then the total charge/current would be infinite. Use this to show that the charge $Q$ integrated over all space (but not time) is **conserved** (meaning it is independent of time). In equations $Q=\int \rho\ dx\wedge dy\wedge dz$ and $\partial Q/\partial t=  0$. ... 

# FINISH THIS
